// Districts of Bangladesh
export const districts = [
  { id: 1, name: "Dhaka" },
  { id: 2, name: "Chittagong" },
  { id: 3, name: "Rajshahi" },
  { id: 4, name: "Khulna" },
  { id: 5, name: "Sylhet" },
  { id: 6, name: "Barisal" },
  { id: 7, name: "Rangpur" },
  { id: 8, name: "Mymensingh" },
  { id: 9, name: "Comilla" },
  { id: 10, name: "Gazipur" },
  { id: 11, name: "Narayanganj" },
  { id: 12, name: "Bogra" },
  { id: 13, name: "Cox's Bazar" },
  { id: 14, name: "Jessore" },
  { id: 15, name: "Dinajpur" },
  { id: 16, name: "Brahmanbaria" },
  { id: 17, name: "Tangail" },
  { id: 18, name: "Narsingdi" },
  { id: 19, name: "Savar" },
  { id: 20, name: "Faridpur" },
  { id: 21, name: "Kishoreganj" },
  { id: 22, name: "Manikganj" },
  { id: 23, name: "Munshiganj" },
  { id: 24, name: "Rajbari" },
  { id: 25, name: "Shariatpur" },
  { id: 26, name: "Madaripur" },
  { id: 27, name: "Feni" },
  { id: 28, name: "Noakhali" },
  { id: 29, name: "Chandpur" },
  { id: 30, name: "Lakshmipur" },
  { id: 31, name: "Khagrachhari" },
  { id: 32, name: "Rangamati" },
  { id: 33, name: "Bandarban" },
  { id: 34, name: "Pabna" },
  { id: 35, name: "Natore" },
  { id: 36, name: "Naogaon" },
  { id: 37, name: "ChapaiNawabganj" },
  { id: 38, name: "Sirajganj" },
  { id: 39, name: "Joypurhat" },
  { id: 40, name: "Satkhira" },
  { id: 41, name: "Magura" },
  { id: 42, name: "Jhenaidah" },
  { id: 43, name: "Chuadanga" },
  { id: 44, name: "Kushtia" },
  { id: 45, name: "Bagerhat" },
  { id: 46, name: "Narail" },
  { id: 47, name: "Meherpur" },
  { id: 48, name: "Habiganj" },
  { id: 49, name: "Moulvibazar" },
  { id: 50, name: "Sunamganj" },
  { id: 51, name: "Bhola" },
  { id: 52, name: "Jhalokati" },
  { id: 53, name: "Patuakhali" },
  { id: 54, name: "Pirojpur" },
  { id: 55, name: "Barguna" },
  { id: 56, name: "Kurigram" },
  { id: 57, name: "Lalmonirhat" },
  { id: 58, name: "Nilphamari" },
  { id: 59, name: "Gaibandha" },
  { id: 60, name: "Thakurgaon" },
  { id: 61, name: "Panchagarh" },
  { id: 62, name: "Jamalpur" },
  { id: 63, name: "Sherpur" },
  { id: 64, name: "Netrokona" },
];

// Upazilas mapped to Districts
export const upazilas = {
  Comilla: [
    "Debidwar",
    "Barura",
    "Brahmanpara",
    "Chandina",
    "Chauddagram",
    "Daudkandi",
    "Homna",
    "Laksam",
    "Muradnagar",
    "Nangalkot",
    "Comilla Sadar",
    "Meghna",
    "Monohargonj",
    "Sadarsouth",
    "Titas",
    "Burichang",
    "Lalmai",
  ],
  Feni: [
    "Chhagalnaiya",
    "Feni Sadar",
    "Sonagazi",
    "Fulgazi",
    "Parshuram",
    "Daganbhuiyan",
  ],
  Brahmanbaria: [
    "Brahmanbaria Sadar",
    "Kasba",
    "Nasirnagar",
    "Sarail",
    "Ashuganj",
    "Akhaura",
    "Nabinagar",
    "Bancharampur",
    "Bijoynagar",
  ],
  Rangamati: [
    "Rangamati Sadar",
    "Kaptai",
    "Kawkhali",
    "Baghaichari",
    "Barkal",
    "Langadu",
    "Rajasthali",
    "Belaichari",
    "Juraichari",
    "Naniarchar",
  ],
  Noakhali: [
    "Noakhali Sadar",
    "Companiganj",
    "Begumganj",
    "Hatia",
    "Subarnachar",
    "Kabirhat",
    "Senbug",
    "Chatkhil",
    "Sonaimori",
  ],
  Chandpur: [
    "Haimchar",
    "Kachua",
    "Shahrasti",
    "Chandpur Sadar",
    "Matlab South",
    "Hajiganj",
    "Matlab North",
    "Faridgonj",
  ],
  Lakshmipur: [
    "Lakshmipur Sadar",
    "Kamalnagar",
    "Raipur",
    "Ramgati",
    "Ramganj",
  ],
  Chittagong: [
    "Rangunia",
    "Sitakunda",
    "Mirsharai",
    "Patiya",
    "Sandwip",
    "Banshkhali",
    "Boalkhali",
    "Anwara",
    "Chandanaish",
    "Satkania",
    "Lohagara",
    "Hathazari",
    "Fatikchhari",
    "Raozan",
    "Karnafuli",
  ],
  "Cox's Bazar": [
    "Coxsbazar Sadar",
    "Chakaria",
    "Kutubdia",
    "Ukhiya",
    "Moheshkhali",
    "Pekua",
    "Ramu",
    "Teknaf",
  ],
  Khagrachhari: [
    "Khagrachhari Sadar",
    "Dighinala",
    "Panchari",
    "Laxmichhari",
    "Mohalchari",
    "Manikchari",
    "Ramgarh",
    "Matiranga",
    "Guimara",
  ],
  Bandarban: [
    "Bandarban Sadar",
    "Alikadam",
    "Naikhongchhari",
    "Rowangchhari",
    "Lama",
    "Ruma",
    "Thanchi",
  ],
  Sirajganj: [
    "Belkuchi",
    "Chauhali",
    "Kamarkhand",
    "Kazipur",
    "Raigonj",
    "Shahjadpur",
    "Sirajganj Sadar",
    "Tarash",
    "Ullapara",
  ],
  Pabna: [
    "Sujanagar",
    "Ishurdi",
    "Bhangura",
    "Pabna Sadar",
    "Bera",
    "Atghoria",
    "Chatmohar",
    "Santhia",
    "Faridpur",
  ],
  Bogra: [
    "Kahaloo",
    "Bogra Sadar",
    "Shariakandi",
    "Shajahanpur",
    "Dupchanchia",
    "Adamdighi",
    "Nondigram",
    "Sonatala",
    "Dhunot",
    "Gabtali",
    "Sherpur",
    "Shibganj",
  ],
  Rajshahi: [
    "Paba",
    "Durgapur",
    "Mohonpur",
    "Charghat",
    "Puthia",
    "Bagha",
    "Godagari",
    "Tanore",
    "Bagmara",
  ],
  Natore: [
    "Natore Sadar",
    "Singra",
    "Baraigram",
    "Bagatipara",
    "Lalpur",
    "Gurudaspur",
    "Naldanga",
  ],
  Joypurhat: ["Akkelpur", "Kalai", "Khetlal", "Panchbibi", "Joypurhat Sadar"],
  ChapaiNawabganj: [
    "Chapainawabganj Sadar",
    "Gomostapur",
    "Nachol",
    "Bholahat",
    "Shibganj",
  ],
  Naogaon: [
    "Mohadevpur",
    "Badalgachi",
    "Patnitala",
    "Dhamoirhat",
    "Niamatpur",
    "Manda",
    "Atrai",
    "Raninagar",
    "Naogaon Sadar",
    "Porsha",
    "Sapahar",
  ],
  Jessore: [
    "Manirampur",
    "Abhaynagar",
    "Bagherpara",
    "Chougachha",
    "Jhikargacha",
    "Keshabpur",
    "Jessore Sadar",
    "Sharsha",
  ],
  Satkhira: [
    "Assasuni",
    "Debhata",
    "Kalaroa",
    "Satkhira Sadar",
    "Shyamnagar",
    "Tala",
    "Kaliganj",
  ],
  Meherpur: ["Mujibnagar", "Meherpur Sadar", "Gangni"],
  Narail: ["Narail Sadar", "Lohagara", "Kalia"],
  Chuadanga: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
  Kushtia: [
    "Kushtia Sadar",
    "Kumarkhali",
    "Khoksa",
    "Mirpur",
    "Daulatpur",
    "Bheramara",
  ],
  Magura: ["Shalikha", "Sreepur", "Magura Sadar", "Mohammadpur"],
  Khulna: [
    "Paikgasa",
    "Fultola",
    "Digholia",
    "Rupsha",
    "Terokhada",
    "Dumuria",
    "Botiaghata",
    "Dakop",
    "Koyra",
  ],
  Bagerhat: [
    "Fakirhat",
    "Bagerhat Sadar",
    "Mollahat",
    "Sarankhola",
    "Rampal",
    "Morrelganj",
    "Kachua",
    "Mongla",
    "Chitalmari",
  ],
  Jhenaidah: [
    "Jhenaidah Sadar",
    "Shailkupa",
    "Harinakundu",
    "Kaliganj",
    "Kotchandpur",
    "Moheshpur",
  ],
  Jhalakathi: ["Jhalakathi Sadar", "Kathalia", "Nalchity", "Rajapur"],
  Patuakhali: [
    "Bauphal",
    "Patuakhali Sadar",
    "Dumki",
    "Dashmina",
    "Kalapara",
    "Mirzaganj",
    "Galachipa",
    "Rangabali",
  ],
  Pirojpur: [
    "Pirojpur Sadar",
    "Nazirpur",
    "Kawkhali",
    "Zianagar",
    "Bhandaria",
    "Mathbaria",
    "Nesarabad",
  ],
  Barisal: [
    "Barisal Sadar",
    "Bakerganj",
    "Babuganj",
    "Wazirpur",
    "Banaripara",
    "Gournadi",
    "Agailjhara",
    "Mehendiganj",
    "Muladi",
    "Hizla",
  ],

  Bhola: [
    "Bhola Sadar",
    "Borhan Sddin",
    "Charfesson",
    "Doulatkhan",
    "Monpura",
    "Tazumuddin",
    "Lalmohan",
  ],
  Barguna: [
    "Amtali",
    "Barguna Sadar",
    "Betagi",
    "Bamna",
    "Pathorghata",
    "Taltali",
  ],
  Sylhet: [
    "Balaganj",
    "Beanibazar",
    "Bishwanath",
    "Companiganj",
    "Fenchuganj",
    "Golapganj",
    "Gowainghat",
    "Jaintiapur",
    "Kanaighat",
    "Sylhet Sadar",
    "Zakiganj",
    "Dakshinsurma",
    "Osmaninagar",
  ],
  Moulvibazar: [
    "Barlekha",
    "Kamolganj",
    "Kulaura",
    "Moulvibazar Sadar",
    "Rajnagar",
    "Sreemangal",
    "Juri",
  ],
  Habiganj: [
    "Nabiganj",
    "Bahubal",
    "Ajmiriganj",
    "Baniachong",
    "Lakhai",
    "Chunarughat",
    "Habiganj Sadar",
    "Madhabpur",
  ],
  Sunamganj: [
    "Sunamganj Sadar",
    "South Sunamganj",
    "Bishwambarpur",
    "Chhatak",
    "Jagannathpur",
    "Dowarabazar",
    "Tahirpur",
    "Dharmapasha",
    "Jamalganj",
    "Shalla",
    "Derai",
    "Madhyanagar",
  ],
  Narsingdi: [
    "Belabo",
    "Monohardi",
    "Narsingdi Sadar",
    "Palash",
    "Raipura",
    "Shibpur",
  ],
  Gazipur: ["Kaliganj", "Kaliakair", "Kapasia", "Gazipur Sadar", "Sreepur"],
  Shariatpur: [
    "Shariatpur Sadar",
    "Naria",
    "Zajira",
    "Gosairhat",
    "Bhedarganj",
    "Damudya",
  ],
  Narayanganj: [
    "Araihazar",
    "Bandar",
    "Narayanganj Sadar",
    "Rupganj",
    "Sonargaon",
  ],
  Tangail: [
    "Basail",
    "Bhuapur",
    "Delduar",
    "Ghatail",
    "Gopalpur",
    "Madhupur",
    "Mirzapur",
    "Nagarpur",
    "Sakhipur",
    "Tangail Sadar",
    "Kalihati",
    "Dhanbari",
  ],
  Kishoreganj: [
    "Itna",
    "Katiadi",
    "Bhairab",
    "Tarail",
    "Hossainpur",
    "Pakundia",
    "Kuliarchar",
    "Kishoreganj Sadar",
    "Karimgonj",
    "Bajitpur",
    "Austagram",
    "Mithamoin",
    "Nikli",
  ],
  Manikganj: [
    "Harirampur",
    "Saturia",
    "Manikganj Sadar",
    "Gior",
    "Shibaloy",
    "Doulatpur",
    "Singiar",
  ],
  Dhaka: ["Savar", "Dhamrai", "Keraniganj", "Nawabganj", "Dohar"],
  Munshiganj: [
    "Munshiganj Sadar",
    "Sreenagar",
    "Sirajdikhan",
    "Louhajanj",
    "Gajaria",
    "Tongibari",
  ],
  Rajbari: ["Rajbari Sadar", "Goalanda", "Pangsa", "Baliakandi", "Kalukhali"],
  Madaripur: ["Madaripur Sadar", "Shibchar", "Kalkini", "Rajoir", "Dasar"],
  Gopalganj: [
    "Gopalganj Sadar",
    "Kashiani",
    "Tungipara",
    "Kotalipara",
    "Muksudpur",
  ],
  Faridpur: [
    "Faridpur Sadar",
    "Alfadanga",
    "Boalmari",
    "Sadarpur",
    "Nagarkanda",
    "Bhanga",
    "Charbhadrasan",
    "Madhukhali",
    "Saltha",
  ],
  Panchagarh: ["Panchagarh Sadar", "Debiganj", "Boda", "Atwari", "Tetulia"],
  Dinajpur: [
    "Nawabganj",
    "Birganj",
    "Ghoraghat",
    "Birampur",
    "Parbatipur",
    "Bochaganj",
    "Kaharol",
    "Fulbari",
    "Dinajpur Sadar",
    "Hakimpur",
    "Khansama",
    "Birol",
    "Chirirbandar",
  ],
  Lalmonirhat: [
    "Lalmonirhat Sadar",
    "Kaliganj",
    "Hatibandha",
    "Patgram",
    "Aditmari",
  ],
  Nilphamari: [
    "Syedpur",
    "Domar",
    "Dimla",
    "Jaldhaka",
    "Kishorganj",
    "Nilphamari Sadar",
  ],
  Gaibandha: [
    "Sadullapur",
    "Gaibandha Sadar",
    "Palashbari",
    "Saghata",
    "Gobindaganj",
    "Sundarganj",
    "Phulchari",
  ],
  Thakurgaon: [
    "Thakurgaon Sadar",
    "Pirganj",
    "Ranisankail",
    "Haripur",
    "Baliadangi",
  ],
  Rangpur: [
    "Rangpur Sadar",
    "Gangachara",
    "Taragonj",
    "Badargonj",
    "Mithapukur",
    "Pirgonj",
    "Kaunia",
    "Pirgacha",
  ],
  Kurigram: [
    "Kurigram Sadar",
    "Nageshwari",
    "Bhurungamari",
    "Phulbari",
    "Rajarhat",
    "Ulipur",
    "Chilmari",
    "Rowmari",
    "Charrajibpur",
  ],
  Sherpur: ["Sherpur Sadar", "Nalitabari", "Sreebordi", "Nokla", "Jhenaigati"],
  Mymensingh: [
    "Fulbaria",
    "Trishal",
    "Bhaluka",
    "Muktagacha",
    "Mymensingh Sadar",
    "Dhobaura",
    "Phulpur",
    "Haluaghat",
    "Gouripur",
    "Gafargaon",
    "Iswarganj",
    "Nandail",
    "Tarakanda",
  ],
  Jamalpur: [
    "Jamalpur Sadar",
    "Melandah",
    "Islampur",
    "Dewangonj",
    "Sarishabari",
    "Madarganj",
    "Bokshiganj",
  ],
  Netrokona: [
    "Barhatta",
    "Durgapur",
    "Kendua",
    "Atpara",
    "Madan",
    "Khaliajuri",
    "Kalmakanda",
    "Mohongonj",
    "Purbadhala",
    "Netrokona Sadar",
  ],
};

// Blood Groups
export const bloodGroups = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];
